<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGvbluTH\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGvbluTH/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGvbluTH.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGvbluTH\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGvbluTH\App_KernelDevDebugContainer([
    'container.build_hash' => 'GvbluTH',
    'container.build_id' => '2743a35b',
    'container.build_time' => 1632122956,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGvbluTH');
