<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWyDwHEt\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWyDwHEt/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWyDwHEt.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWyDwHEt\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWyDwHEt\App_KernelDevDebugContainer([
    'container.build_hash' => 'WyDwHEt',
    'container.build_id' => '265459c2',
    'container.build_time' => 1631543719,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWyDwHEt');
